pipeline {
    agent any 
        
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    
    stages {
        stage ('Compile') {
            steps {
              sh label: 'Compilar codigo', script: './calculator/gradlew compileJava'
            }        
        }

        stage ('Unit Tests') {
            steps {
              sh label: 'Ejecutar test unitarios', script: './ calculator/gradlew test'
            }
        }
    }
      post {
        cleanup {
            //Clean Workspace
            cleanWs()
        }
    }
}

